### ISSUE TITLE
OBS Plugin

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#145]
OBS Supports web-view style plugins. We can probably make something pretty cool.

**Comment by marysiamzawka** [comment]
Possibilities:
- Recent play list
- Live Sieglinde display
- Recent Rivals plays
- Live site ranking display
- Current session stats
- Live folder overview

**Comment by zkldi** [comment]
As cool as this is, I'm never going to take this on. I'm far too busy and bad at design to make something like this. Consider this an open bounty.
