### ISSUE TITLE
BeatorajaIR Dynamic Tables

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#17]
By using beatoraja's table functionality, we can create dynamic pseudo-tables based on some things users have going on. This might open the door for some interesting concepts.

We don't have to actually honour the concept of a table being an ascending list of folders, but rather take advantage of the fact that we can just create folders dynamically -- things your rivals have played recently, things you've highlighted recently, etc, **definitely** challenge integration.

We'll see.

**Comment by Mobiuslau** [comment]
Another idea for this table could be to include the Genoside dan courses such that Bokutachi users can be sure their results are submitted and accepted, and they wouldn't have to search for other tables to obtain the courses.

**Comment by zkldi** [comment]
moved to 2.3

**Comment by zkldi** [comment]
Blocked by #753

**Comment by zkldi** [comment]
infrastructure for this is live
