### ISSUE TITLE
Bot stopped responding to commands

### ISSUE THREAD

**Issue by Void345** [TNG-dev/Tachi#385]
Tried to do /last_session and it didn't work, thought the issue might be on my end so i tried /faq and it still didn't work
![image](https://user-images.githubusercontent.com/43857511/178256898-1c22446d-0ce6-4a04-9dd9-a9c75f617b67.png)

**Comment by JustVldKsh** [comment]
Can confirm the issue, does not work for me either!
[IMG_20220711_184801.jpg](https://user-images.githubusercontent.com/49518100/178257698-504ec692-40dd-48f3-a03c-cebec87eaf8b.jpg)

**Comment by zkldi** [comment]
seq logging now applies to the bot so finally these errors are actually reported to someone.

i'll get around to looking into a patch for this soon.

**Comment by zkldi** [comment]
bot was remarkably unstable. should probably be fine now.
