### ISSUE TITLE
SDVX1-2 Converts for USC have incorrect levels on the site

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#607]
Amusing note: The checksums used by USC include the chart level; this means that people playing the game cannot change their levels locally, or they will no longer have the same chart checksum as everyone else. Wonderful!

However, we can change this in the seeds and it will propogate fine in the UI (and fix some faulty VF calcing)

**Comment by cg505** [comment]
We should accept both the original file hash and the hash of the file with the changed difficulty.

**Comment by cg505** [comment]
yeah it's been in my head for a while but I just haven't put in the efforta

**Comment by cg505** [comment]
Also, it's quite common that people actually have modified their chart levels (I have). There is a program to do exactly that.

**Comment by zkldi** [comment]
ah for fucks sake
