### ISSUE TITLE
Document how to contribute to Tachi Seeds

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#613]
Properly, and ideally such that people with minimal programming experience but maximal game experience can contribute back.

They need to know:

-> how to git
-> how to json
-> what a song/chart look like
-> how to maybe script some stuff

**Comment by justOkapi** [comment]
would be very helpful for me since I'm not smart and do it all by hand

**Comment by zkldi** [comment]
Mostly done.

Still left to do:

[] JSON Guide
[] Git Primer
[] Core Contribution Guide (Client, Server) + architecture discussion.
