### ISSUE TITLE
Spotty AI table support

### ISSUE THREAD

**Issue by marysiamzawka** [TNG-dev/Tachi#635]
![image](https://user-images.githubusercontent.com/20336327/185515503-9c0168ad-bac1-4229-9966-39fd5fcc7b4d.png)

Apparently not all charts are picked up by the AI table of Bokutachi.
These two are present in the table (rated as Normal 7 and Insane 1 respectively)

**Comment by zkldi** [comment]
Those charts are probably recent enough that they were added to the Bokutachi DB between me setting up the AI table and now.

The AI table *should* automatically update itself, although I'm not sure it is at the moment.

**Comment by marysiamzawka** [comment]
> Those charts are probably recent enough that they were added to the Bokutachi DB between me setting up the AI table and now.

These are from the last BOF and PABAT events respectively, so at this point they're more than 4 months old

**Comment by zkldi** [comment]
sounds right, the data locally is very out of date

**Comment by zkldi** [comment]
will now automatically update.
