### ISSUE TITLE
Sieglinde Tables in-game

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#643]
Make actual tables for the sieglinde things so people can use them in game a-la walkure suggestions. I guess.

**Comment by Mobiuslau** [comment]
Do you mean a 'static' table similar to existing normal and insane tables, or a table which specifically contains recommendations for each player?

**Comment by zkldi** [comment]
static tables ideally. maybe player specific recommendations can come at some point, but that'll fall under #17.
