### ISSUE TITLE
Heuristics to detect whether someone is sending jubeat score / 10k as percent

### ISSUE THREAD

**Issue by zkldi** [TNG-dev/Tachi#722]
since someone just fell for this
and inevitably more people will

this should be a case of more than 5 scores, all of them are jubeat score / 10k

**Comment by cg505** [comment]
at the moment, are there anyway to add validators that apply to all dryScores? eg, usually each converter will have some sanity checks like perfect score equals perfect lamp. is there already a mechanism for doing this at the game level rather than the import type level?

**Comment by zkldi** [comment]
this is planned (I think there's a related issue) and it's generally pretty important to have. It's like a missing third step in the import process (parse -> convert -> validate!)

It's not possible at the moment though.

**Comment by zkldi** [comment]
Update: there's no related issue. I've made one here: #724

**Comment by zkldi** [comment]
Meld with #724
