### ISSUE TITLE
Add exporting IIDX Quests as playlister-compatible .json files

### ISSUE THREAD

**Issue by marysiamzawka** [TNG-dev/Tachi#806]
This would allow for better in-game integration of quests and goals.
The playlister .json format is documented in the 🐽 thread

A playlist would contain folders only for specific timing/clear goals, for example the `Approaching Chuuden` playlist would have `HARD CLEAR`, `CLEAR`, `AAA` and `MAX-` folders.
For a `CLEAR any one of` type of a goal, a separate folder with just these charts would be created.

**Comment by zkldi** [comment]
Playlist names are capped at 15 characters. I'm not sure how i would squish a quest name and criteria into 15 chars. `HC Approaching Chuuden` is still *wayyy* over the limit.

**Comment by marysiamzawka** [comment]
Assuming that the longest "goal" name would be something like `MAX- ANY` the quest lists could have a 6-char (+1 for whitespace) user-definiable "truncated name" string
so for example "Approaching Chuuden HC" becomes `CHUU HC`
or "Post-Kaiden VI Get a score of 3700" becomes `POST-6 3700EX` (i know this sounds stupid but I'm trying to work within the limit)

**Comment by zkldi** [comment]
that can work, but my opposition to this is that it's kind of a square peg and a round hole:

- This would result in (potentially) hundreds of playlists being added, likely with one goal in each.
- Quest names can be completely arbitrary, we'd have to hardcode a "short name" for each quest name to be used in this context, which I don't really feel like doing.

**Comment by zkldi** [comment]
going to close this because (although i think it would be awesome) it's not possible to implement given the current restrictions.
